<../../../mkconfig

TARG=\

SHTARG=\
		spreeclient.sh\

MODULES=\

SYSMODULES= \

DISBIN=$ROOT/dis/demo/spree

SHFILES=${SHTARG:%.sh=$DISBIN/%}

all:V: $SHTARG
install:V:	$SHFILES
clean:V:
	rm -f *.dis *.sbl
nuke:V:	clean
	rm -f $SHFILES
all:V: $SHTARG
install:V:	$SHFILES
%.install:V:	$DISBIN/%
%.installall:V:	$DISBIN/%

$DISBIN/%:	%.sh
	cp $stem.sh $target && chmod a+rx $target
