<$ROOT/mkconfig

KRYON=/dis/kryon.dis

KRYFILES=\
	about.kry\
	bounce.kry\
	clock.kry\
	date.kry\

BFILES=${KRYFILES:%.kry=%.b}

DISFILES=${KRYFILES:%.kry=%.dis}

all:V:	$BFILES $DISFILES

%.b:	%.kry	$KRYON
	limbo $KRYON $stem.kry

%.dis:	%.b
	limbo -g $stem.b

clean:V:
	rm -f $BFILES $DISFILES

install:V: all

nuke:V: clean
