<$ROOT/mkconfig

TARG=kryon.dis

MODULES=\
	ast.m\
	lexer.m\
	parser.m\
	codegen.m\

SYSMODULES=\
	sys.m\
	draw.m\
	bufio.m\

DISBIN=$ROOT/dis

<$ROOT/mkfiles/mkdis

install:V:
	rm -f $DISBIN/kryon.dis && cp kryon.dis $DISBIN/kryon.dis
