<../mkconfig

TARG=kryonc

OFILES=\
	main.$O\
	parse/ast.$O\
	parse/lexer.$O\
	parse/y.tab.$O\
	gen/limbo.$O\

HFILES=\
	parse/ast.h\
	parse/lexer.h\
	parse/y.tab.h\
	gen/codegen.h\

LIBS=9

YFILES=parse/parser.y

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE

CFLAGS=$CFLAGS -Iparse -Igen

parse/y.tab.h parse/y.tab.c: $YFILES
	$YACC $YFLAGS $YFILES
	mv y.tab.c parse/y.tab.c
	mv y.tab.h parse/y.tab.h

parse/lexer.$O: parse/lexer.c parse/y.tab.h
